export const LINK = {
  HOME: "Home",
  MAIN: "Main",
  KAKAO_LOGIN_PAGE: "KakaoLoginPage",
  EXPLORE_PAGE: "ExplorePage",
  TRIP_DETAIL_PAGE: "PostDetail",
  CREATE_POST_PAGE: "CreatePost",
  UPDATE_POST_PAGE: "UpdatePost",
  USER_PAGE: "UserPage",
  MY_PAGE: "MyPage",
  FOLLOWER_PAGE: "FollowerPage",
  FOLLOWING_PAGE: "FollowingPage",
  EDIT_PROFILE_PAGE: "EditProfilePage",
  NOTIFICATION_PAGE: "NotificationPage",
  AUTH_CONFIRM: "AuthConfirm",
  SETUP: {
    SETUP_PAGE: "SetupPage",
    PUSH_NOTIFICATION_SETUP_PAGE: "PushNotificationSetupPage",
    OPENSOURCE_LICENCE_PAGE: "OpensourceLicencePage",
    OPENSOURCE_LICENCE_DETAIL_PAGE: "OpensourceLicenceDetailPage",
    PRIVACY_POLICY_PAGE: "PrivacyPolicyPage",
    LOCATION_POLICY_PAGE: "LocationPolicyPage",
    POST_MANAGEMENT_POLICY_PAGE: "PostManagementPolicyPage",
    ACCOUNT_MANAGEMENT_PAGE: "AccountManagementPage",
  },
};
